version: '3.8'

services:
  server:
    image: blog-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 3003:3000
    env_file:
      - ./backend/.env

  app:
    image: blog-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3003
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3000:3000