name: tests for frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

defaults:
  run:
    working-directory: ./frontend

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: npm install
        run: npm install
      - name: npm run eslint
        run: npm run eslint
      - name: npm test
        run: npm test
